### PR TITLE
improving "healthcheck"

### LINKED ISSUE #9: Improve Healthcheck
Add version number to healthcheck.

### PR DESCRIPTION
**Pull request by gvn**
closes #9

### CODE REVIEW

**Comment by flukeout** [comment]
image

**Comment by gvn** [comment]
So, to explain a bit: when you run `npm build` (or a build gets triggered from `npm start`) this will make a text file called `healthcheck.txt` with the version number and build time. This way we can see what version is up on staging (and it also helps trigger live reload by being the last step in the build process).

**Comment by gvn** [comment]
Also, FYI: Travis will fail until we clean up the SCSS, so you can ignore it for now...

**Comment by flukeout** [comment]
Ok, let me know when I can help with this!

**Pull request merged**
